In [4]:
import numpy as np

# NdArray

In [6]:
# N- Dimensional Array 
a= np.array([1,2,3])
print(a)

[1 2 3]


# Creation of Arrays

In [15]:
a=np.array([[[1,2,3],
            [1,2,3],
            [4,5,6]],
            
            [[1,2,3],
            [1,2,3],
            [4,5,6]]])
a.shape

(2, 3, 3)

# Basic Operations

In [65]:
b=np.zeros((10), dtype="int64")
b=np.ones((10), dtype="int64")
b=np.arange(0,10).reshape(5,2) #2*5 => 10 
b=np.linspace(0,10,1000)
b=np.random.random((3,3))


#Arithmetic Operators


a=np.array([[1,2,3],
           [4,5,6],
           [8,9,0]])

b=np.array([[1,2,3],
           [4,5,6],
           [8,9,0]])
# Element-wise operations

r= np.arange(0,10)


# Matrix Product
np.dot(a,b)

#Increment and Decrement Operations


print(a)

[[1 2 3]
 [4 5 6]
 [8 9 0]]


# Universal Functions

In [93]:
b=np.sqrt(b)
b=np.sin(a)

#Aggregate Functions -> Single Result
r= np.arange(0,10)
a.std()

#Indexing



# Slicing

  # Start: Ending  (3,3) => (Row, Column)


# Iteration

for i in a.flat:
    print(i)

1
2
3
4
5
6
8
9
0


/home/ali/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


# Array Manipulation

In [110]:
# imagea=np.zeros((10,10))
# imageb=np.ones((10,10))
# np.hstack((imageb,imagea,))

# a=np.array([1,2,0,3])
# b=np.array([4,5,6])
# np.row_stack((a,b))



np.split(a,[1,3])

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int64)]

# Array Broadcasting

In [112]:
a=np.arange(16).reshape(4,4)
b=np.arange(10).reshape(2,5)
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (2,5) 